# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_exam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
